### ISSUE TITLE
New honk & flash icon requested

### ISSUE THREAD

**Issue by almaven** [porscheui/porsche-design-system-contribution#1]
**Scope**  
Currently on (new) car control site icon with horn is used for honk and flash action.
![Flash_honk flash](https://user-images.githubusercontent.com/42635092/55065649-8475f300-507c-11e9-9f3b-b3e95f17f141.png)
Request: new icon for honk and flash, as mix of both available icons.

**Notes**  
- for decision/approval please contact Emre Eliguezel.

**Props** (if relevant)  
- Name: Honk&Flash
- States: same as present icons
- Variants: mix of two current icons
- Cases/Templates: same as present icons
- Themes: same as present icons

**Comment by annakrohmer** [comment]
Hi @almaven ! 

First of all: Sorry for the delayed response – I was unfortunately out of office for a few days due to illness. 

If I get you right, you request a new SVG icon for "honk & flash", correct? Actually, this seems to be a very specific icon, so I recommend that you design the icon yourself and use it project-specifically in the first place, as we aim to provide only general elements within the Porsche UI Kit (and, moreover, are expecting a larger icon update in the future, which will affect not only the icon range and visual style, but also an updated, smart way how the icons are provided).

Anyhow: We are very happy to answer any questions and give you review support, for sure – feel free to ask! :)
